// Generated by backend/toggle.mjs — do not edit by hand.
// DataUtils reads this to decide which endpoints it talks to.
// Valid values: "mock" | "standard"
export const DATA_SOURCE: "mock" | "standard" = "mock";
