// HOW TO RUN THE TOGGLE (from the skillswap/ project root):
//
//   npm run toggle -- mock        # Read seeded mock data plus published events
//   npm run toggle -- standard    # Read only the standard datasets
//   npm run toggle                # no argument: just print the current data source
//
// You can also call the script directly, e.g.:
//   node backend/toggle.mjs mock
//
// What it does: rewrites backend/dataSource.ts. DataUtils imports DATA_SOURCE from
// that file to choose its read endpoints. New listings always publish to
// /events.json. With `next dev` running, refresh the browser after toggling.

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const DATA_SOURCE_FILE = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "dataSource.ts",
);

const VALID_SOURCES = ["mock", "standard"];

function template(source) {
  return `// Generated by backend/toggle.mjs — do not edit by hand.
// DataUtils reads this to decide which endpoints it talks to.
// Valid values: "mock" | "standard"
export const DATA_SOURCE: "mock" | "standard" = "${source}";
`;
}

/**
 * Switch which datasets DataUtils reads.
 * @param {"mock"|"standard"} dataSource
 */
export async function toggle(dataSource) {
  if (!VALID_SOURCES.includes(dataSource)) {
    throw new Error(
      `Invalid data source "${dataSource}". Use one of: ${VALID_SOURCES.join(", ")}.`,
    );
  }
  await writeFile(DATA_SOURCE_FILE, template(dataSource), "utf8");

  const files =
    dataSource === "mock"
      ? "tasksMock.json, eventsMock.json, and published events.json"
      : "backend/dataStorage/tasks.json & backend/dataStorage/events.json";
  console.log(`DataUtils data source → ${dataSource}`);
  console.log(`DataUtils will now read: ${files}`);
  console.log("New listings will publish to backend/dataStorage/events.json.");
  console.log("Refresh the browser if the dev server is running.");
}

/** Best-effort read of the current value written into backend/dataSource.ts. */
async function currentSource() {
  try {
    const raw = await readFile(DATA_SOURCE_FILE, "utf8");
    const match = raw.match(/= "([^"]+)"/);
    return match ? match[1] : "unknown";
  } catch {
    return "unknown";
  }
}

async function main() {
  const arg = process.argv[2];

  if (!arg) {
    console.log(`Current data source: ${await currentSource()}`);
    console.log("");
    console.log("Usage:");
    console.log(
      "  npm run toggle -- mock        → read mock data plus published events",
    );
    console.log(
      "  npm run toggle -- standard    → read the standard datasets",
    );
    return;
  }

  try {
    await toggle(arg);
  } catch (err) {
    console.error(err.message);
    process.exitCode = 1;
  }
}

// Run the CLI when executed directly (works when imported too).
const isCli =
  process.argv[1] &&
  path.resolve(process.argv[1]).toLowerCase() ===
    path.resolve(fileURLToPath(import.meta.url)).toLowerCase();
if (isCli) {
  main();
}
